apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: advent
  labels:
    app: advent
    role: static
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  tls:
    - hosts:
      - advent.dekiru.tech
  rules:
    - host: advent.dekiru.tech
      http:
        paths:
          - backend:
              service:
                name: advent
                port:
                  name: http
            path: /
            pathType: prefix
